theme: jekyll-theme-architect

# Where things are
source              : ./writing
destination         : ./writing/_site
collections_dir     : ./writing/_collections
plugins_dir         : ./writing/_plugins
layouts_dir         : ./writing/_layouts
data_dir            : ./writing/_data
includes_dir        : ./writing/_includes
