#theme: jekyll-theme-architect

# Where things are
source              : ./writing
destination         : ./writing/_site
collections_dir     : ./writing/_collections
plugins_dir         : ./writing/_plugins
layouts_dir         : ./writing/_layouts
data_dir            : ./writing/_data
includes_dir        : ./writing/_includes

# Site
name: 'Page of Jahirul Islam'
description: 'Welcome to page of Md. Jahirul Islam Bhuiyan'
logo: 'writing/assets/images/logo.png'
favicon: 'writing/assets/images/logo.png'
baseurl: '/writing'
avatar: 'writing/assets/images/sal.jpg'
disqus: 'rajumjib'
email: '0nline4help@gmail.com'

include: ["writing/_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "writing/_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "writing/_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]